### ISSUE TITLE
Lua debugger crash

### ISSUE THREAD

**Issue by stuta** [libvips/lua-vips#16]
I'm using ZeroBraneStudio (latest git version). When I create image and put cursor on top of image variable or put image variable to variable watch then debugger will crash. I think image needs __tostring() metamethod.

```lua
local image = vips.Image.new_from_file(path)
```

**Comment by jcupitt** [comment]
There's a `__tostring()` here:

https://github.com/jcupitt/lua-vips/blob/master/src/vips/Image_methods.lua#L329

You can see it working in eg.:

```
$ luajit
LuaJIT 2.0.4 -- Copyright (C) 2005-2015 Mike Pall. http://luajit.org/
JIT: ON CMOV SSE2 SSE3 SSE4.1 fold cse dce fwd dse narrow loop abc sink fuse
> vips = require("vips")
> x = vips.Image.new_from_file("/home/john/pics/k2.jpg")
> print(x)
/home/john/pics/k2.jpg: 1450x2048 uchar, 3 bands, srgb, jpegload
> 
```

I'll have a look at ZeroBraneStudio.

**Comment by jcupitt** [comment]
It looks like it's some confusion about array indexing. I don't see a crash, but there is an error message instead of watch text.

lua-vips tries to overload `[]` for band extract, so you can use:

```lua
g = rgb[1]
```

But it follows libvips in numbering bands from 0. If you change:

https://github.com/jcupitt/lua-vips/blob/master/src/vips/Image_methods.lua#L790

to:

```lua
        return table:extract_band(index - 1)
```

ie. number bands from 1, then the debugger starts displaying watch values. But it's not using the `__tostring()`, strangely, instead you see things like:

![screenshot from 2018-02-18 13-04-50](https://user-images.githubusercontent.com/580843/36352153-a4ada13e-14ac-11e8-874c-749a1be3f4ff.png)

**Comment by jcupitt** [comment]
If I set:

```lua
debugger.showtostring = true
```

In my `user.lua` it starts working for me. 

Perhaps we should remove the attempt at `[]` overload? It's seems likely to cause confusion and break things.

**Comment by jcupitt** [comment]
OK, `[]` and `#` overloads removed. Thanks!

**Comment by jcupitt** [comment]
1.1-5 pushed to luarocks with these changes.

**Comment by stuta** [comment]
All works, thanks.
